### ISSUE TITLE
Can't install on VS2015 WHICH HAS NETSTANDARD 2.0.3 INSTALLED

### ISSUE THREAD

**Issue by johncblacker** [Eibwen/SimpleAlphaVantage#1]
I'm trying to install your package using nuget under VS2015 and I get an error:
----------------------------- output error info -----------------------------
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'SimpleAlphaVantage 1.0.1.95340037'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0	
------------------ end of output error info ------------------
Can you help me discover what's wrong?

**Comment by Eibwen** [comment]
Apologies for not seeing this sooner, don't check this email often

From that error, it would appear that your project is targeting 4.5.2

Based on this chart https://dotnet.microsoft.com/platform/dotnet-standard#versions (or less cool version https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support)

And that I currently only have .NetStandard2.0.  The 2.0 standard column, says for full compatibility the minimum is .NetFramework4.6.1

~Now I do not believe this library has any real need for 2.0Standard, so compiling this for 1.2Standard should be an easy task.~ apparently the Serialization attributes that I'm using, how I'm using them, do need 2.0.  But it maybe `net45` would work

So likely options:
* One of us merges a pull request of changing the library `.csproj` from `<TargetFramework>netstandard2.0</TargetFramework>` to `<TargetFrameworks>netstandard2.0;net45</TargetFrameworks>` (wrote that off the top of my head, so completely untested), then the nuget will get updated
* You update your project which is referencing this to 4.6.1 or higher
* You pull the code and build a local version with bullet1 changes to get started coding

**Comment by johncblacker** [comment]
I'm going to try last bullet myself. Thanks.

**Comment by johncblacker** [comment]
You can close if/when you make changes. I'm using VS2010.

**Comment by johncblacker** [comment]
So, I'm not doing something correctly.  I forked this to my own repository, then cloned that to my P/C.  Once there, I changed the "target framework" to netstandard 1.0 and tried to build; however, I'm getting 12 errors about a bunch of namespaces not found, some starting with Http... and others starting with Serial...
Am I missing a step somewhere or can't I do what I tried to do.  My original project in which I want to use your code is targeting 4.5.1.  If I put a target of 4.5.1 into your .csproj I get errors about not being able to load that framework (which doesn't make sense because my project is fine with 4.5.1).  I'm not at all familiar with "netstandard x.x" at all, so bear with my ignorance.

**Comment by johncblacker** [comment]
Tried using netstandard 1.6, but still got 4 errors, changed target to netstandard 2.0 and no errors; so it appears as though you do indeed required netstandard 2.0 to compile this code.  That being said, I don't know how to use the code in my app which targets v4.5.1...

**Comment by johncblacker** [comment]
So, moving right along, I changed my target framework to v.6.1 which is supported by netstandard 2.0, then used nuget to install your package from the nuget online repository and so far, so good.  Now I have to actually put some code in to use your package...

**Comment by johncblacker** [comment]
Also, how do you setup linqpad to perform the sample queries you've listed on the readme

**Comment by johncblacker** [comment]
Tried one of your readme examples in linqpad, added the simplealphavantage.dll to references and got error about namespace 'SimpleAlphaVantage' could not be found...what am I missing?

**Comment by johncblacker** [comment]
Greg,

I brought my app over to VS2017 and changed its target framework to 4.6.1, used nuget to install your code unchanged, then tried something based off your

examples in the README and now I’m stuck.  So, looking at the second (complex) example, this is what I have in my code:

var client = new StockTimeSeriesData(AlphaVantageApiKey);

var results = client.TimeSeriesDailyAdjusted(stock);

 

Just to see what’s in results. As you can see I removed the await and removed the .data in the call to TimeSeriesDailyAdjusted.

I did this because if I were to leave the await in, I’d have to refactor the method in which this code resides, and I’d have to refactor

the code that calls the method, and so on.  I don’t want to do that at this time as I like to make changes in small steps.  So, anyway,

what happens when I run these two lines above is I get nothing in results – at least not what I was expecting – and I guess I can somewhat 

understand that what’s represented by “results” is a asynchronous task?  And, thus, your having the “.data” part in the call in order to 

extract the tasks data?

 

So, how can I use your code without using the await and “.data” parts, or is it simply (no pun intended) not possible.  If it’s not

possible, then I’ll have to decide whether to use your code and refactor my whole method or I’ll have to find something else to use.

 

Please let me know if it’s possible to use your code without the “await” and “.data” in the call; and, if so, I’d appreciate some sample 

C# code to do so.

 

Thanks.

John Blacker

**Comment by johncblacker** [comment]
Greg, can you please read my post above again - most recent one.  I'm not targeting 4.6.1 and I've tried using your code without await, but can't get it to work and need help - if it's possible at all.  Thanks.

**Comment by johncblacker** [comment]
Closing...author just doesn't check this area often enough to be of help.

**Comment by Eibwen** [comment]
Apologies for going MIA during a busy and stressful time at work

```
	var client = new StockTimeSeriesData(AlphaVantageApiKey);
	
	var results = client.TimeSeriesIntraday("MSFT", IntradayInterval.HalfHour).Result;
```
Would be one way to get a synchronous version, `GetAwait().GetResults()` is another option

More reading here: https://blog.stephencleary.com/2014/12/a-tour-of-task-part-6-results.html

----

If you're still trying to use this library, I should be slightly more available now.  Alternatively I'd love to know if you found an alternative library?  As I will likely not focus *too* much time or energy to maintaining this project
